[package]
edition = "2018"
name = "board"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "board"

[dependencies]
serde = "1"
derive_more = "0"
chrono = {version = "0.4", features = ["serde"]}

hdk = "0.0.109"
holo_hash = { version = "0.0.8", features = ["encoding"] }
